### ISSUE TITLE
error message (FailedPreconditionError) from train.py via latest tensorflow_gpu 

### ISSUE THREAD

**Issue by yuewu57** [brain-research/acai#12]
Hi,

I tried to run your code for minist database on cluster, where I cannot install tensorflow_gpu==1.8 (_ImportError: libcublas.so.9.0: cannot open shared object file_
). So I installed the latest tensorflow_gpu, and then the error message pompted up:

2019-07-06 11:50:03.069848: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
I0706 11:50:03.083035 140122140165952 session_manager.py:500] Running local_init_op.
I0706 11:50:03.100641 140122140165952 session_manager.py:502] Done running local_init_op.
I0706 11:50:03.797316 140122140165952 basic_session_run_hooks.py:606] Saving checkpoints for 0 into TRAIN/mnist32/AEBaseline_depth16_latent16_scales3/tf/model.ckpt.
2019-07-06 11:50:04.067226: W tensorflow/core/framework/op_kernel.cc:1479] OP_REQUIRES failed at flat_map_dataset_op.cc:36 : Failed precondition: Could not find required function definition __inference_Dataset_flat_map_read_one_file_11
2019-07-06 11:50:04.067304: E tensorflow/core/common_runtime/executor.cc:641] Executor failed to create kernel. Failed precondition: Could not find required function definition __inference_Dataset_flat_map_read_one_file_11
	 [[{{node OptimizeDataset/FlatMapDataset}}]]
2019-07-06 11:50:04.067379: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at iterator_ops.cc:973 : Failed precondition: Could not find required function definition __inference_Dataset_flat_map_read_one_file_11
	 [[{{node OptimizeDataset/FlatMapDataset}}]]
Traceback (most recent call last):
  File "/home/wuy/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/wuy/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/wuy/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Could not find required function definition __inference_Dataset_flat_map_read_one_file_11
	 [[{{node OptimizeDataset/FlatMapDataset}}]]
	 [[OneShotIterator]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "baseline.py", line 104, in <module>
    app.run(main)
  File "/home/wuy/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/wuy/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "baseline.py", line 94, in main
    model.train()
  File "/scratch/wuy/acai-master/lib/train.py", line 162, in train
    self.train_step(data_in, ops)
  File "/scratch/wuy/acai-master/lib/train.py", line 93, in train_step
    x = self.tf_sess.run(data)
  File "/home/wuy/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/wuy/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wuy/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/wuy/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Could not find required function definition __inference_Dataset_flat_map_read_one_file_11
	 [[{{node OptimizeDataset/FlatMapDataset}}]]
	 [[OneShotIterator]]

**Comment by craffel** [comment]
Hi, this does not look like an issue related to ACAI, please open an issue on the official TF repo.
